import PropTypes from 'prop-types';
import classNames from "classnames";

const applyMargin = (props) => {
    return classNames(" ",
        {"uk-margin": props.margin},
        {"uk-margin-top": props.marginTop},
        {"uk-margin-bottom": props.marginBottom},
        {"uk-margin-left": props.marginLeft},
        {"uk-margin-right": props.marginRight},

        {"uk-margin-small": props.marginSmall},
        {"uk-margin-small-top": props.marginTopSmall},
        {"uk-margin-small-bottom": props.marginBottomSmall},
        {"uk-margin-small-left": props.marginLeftSmall},
        {"uk-margin-small-right": props.marginRightSmall},

        {"uk-margin-medium": props.marginMedium},
        {"uk-margin-medium-top": props.marginTopMedium},
        {"uk-margin-medium-bottom": props.marginBottomMedium},
        {"uk-margin-medium-left": props.marginLeftMedium},
        {"uk-margin-medium-right": props.marginRightMedium},

        {"uk-margin-large": props.marginLarge},
        {"uk-margin-large-top": props.marginTopLarge},
        {"uk-margin-large-bottom": props.marginBottomLarge},
        {"uk-margin-large-left": props.marginLeftLarge},
        {"uk-margin-large-right": props.marginRightLarge},

        {"uk-margin-xlarge": props.marginXLarge},
        {"uk-margin-xlarge-top": props.marginTopXLarge},
        {"uk-margin-xlarge-bottom": props.marginBottomXLarge},
        {"uk-margin-xlarge-left": props.marginLeftXLarge},
        {"uk-margin-xlarge-right": props.marginRightXLarge},

        {"uk-margin-remove": props.marginRemove},
        {"uk-margin-remove-top": props.marginRemoveTop},
        {"uk-margin-remove-bottom": props.marginRemoveBottom},
        {"uk-margin-remove-left": props.marginRemoveLeft},
        {"uk-margin-remove-right": props.marginRemoveRight},
        {"uk-margin-remove-vertical": props.marginRemoveVertical},
        {"uk-margin-remove-adjacent": props.marginRemoveAdjacent},
        {"uk-margin-remove-first-child": props.marginRemoveFirstChild},
        {"uk-margin-remove-last-child": props.marginRemoveLastChild},

        {"uk-margin-remove-left@s": props.marginRemoveLeftSmall},
        {"uk-margin-remove-right@s": props.marginRemoveRightSmall},
        {"uk-margin-remove-left@m": props.marginRemoveLeftMedium},
        {"uk-margin-remove-right@m": props.marginRemoveRightMedium},
        {"uk-margin-remove-left@l": props.marginRemoveLeftLarge},
        {"uk-margin-remove-right@l": props.marginRemoveRightLarge},
        {"uk-margin-remove-left@xl": props.marginRemoveLeftXLarge},
        {"uk-margin-remove-right@xl": props.marginRemoveRightXLarge},

        {"uk-margin-auto": props.marginAuto},
        {"uk-margin-auto-top": props.marginAutoTop},
        {"uk-margin-auto-bottom": props.marginAutoBottom},
        {"uk-margin-auto-left": props.marginAutoLeft},
        {"uk-margin-auto-right": props.marginAutoRight},
        {"uk-margin-auto-vertical": props.marginAutoVertical},

        {"uk-margin-auto@s": props.marginAutoSmall},
        {"uk-margin-auto-top@s": props.marginAutoTopSmall},
        {"uk-margin-auto-bottom@s": props.marginAutoBottomSmall},
        {"uk-margin-auto-left@s": props.marginAutoLeftSmall},
        {"uk-margin-auto-right@s": props.marginAutoRightSmall},
        {"uk-margin-auto-vertical@s": props.marginAutoVerticalSmall},

        {"uk-margin-auto@m": props.marginAutoMedium},
        {"uk-margin-auto-top@m": props.marginAutoTopMedium},
        {"uk-margin-auto-bottom@m": props.marginAutoBottomMedium},
        {"uk-margin-auto-left@m": props.marginAutoLeftMedium},
        {"uk-margin-auto-right@m": props.marginAutoRightMedium},
        {"uk-margin-auto-vertical@m": props.marginAutoVerticalMedium},

        {"uk-margin-auto@l": props.marginAutoLarge},
        {"uk-margin-auto-top@l": props.marginAutoTopLarge},
        {"uk-margin-auto-bottom@l": props.marginAutoBottomLarge},
        {"uk-margin-auto-left@l": props.marginAutoLeftLarge},
        {"uk-margin-auto-right@l": props.marginAutoRightLarge},
        {"uk-margin-auto-vertical@l": props.marginAutoVerticalLarge},

        {"uk-margin-auto@xl": props.marginAutoXLarge},
        {"uk-margin-auto-top@xl": props.marginAutoTopXLarge},
        {"uk-margin-auto-bottom@xl": props.marginAutoBottomXLarge},
        {"uk-margin-auto-left@xl": props.marginAutoLeftXLarge},
        {"uk-margin-auto-right@xl": props.marginAutoRightXLarge},
        {"uk-margin-auto-vertical@xl": props.marginAutoVerticalXLarge},

        " "
    );
};

applyMargin.propTypes = {
    margin: PropTypes.bool,
    marginTop: PropTypes.bool,
    marginBottom: PropTypes.bool,
    marginLeft: PropTypes.bool,
    marginRight: PropTypes.bool,

    marginSmall: PropTypes.bool,
    marginTopSmall: PropTypes.bool,
    marginBottomSmall: PropTypes.bool,
    marginLeftSmall: PropTypes.bool,
    marginRightSmall: PropTypes.bool,

    marginMedium: PropTypes.bool,
    marginTopMedium: PropTypes.bool,
    marginBottomMedium: PropTypes.bool,
    marginLeftMedium: PropTypes.bool,
    marginRightMedium: PropTypes.bool,

    marginLarge: PropTypes.bool,
    marginTopLarge: PropTypes.bool,
    marginBottomLarge: PropTypes.bool,
    marginLeftLarge: PropTypes.bool,
    marginRightLarge: PropTypes.bool,

    marginXLarge: PropTypes.bool,
    marginTopXLarge: PropTypes.bool,
    marginBottomXLarge: PropTypes.bool,
    marginLeftXLarge: PropTypes.bool,
    marginRightXLarge: PropTypes.bool,

    marginRemove: PropTypes.bool,
    marginRemoveTop: PropTypes.bool,
    marginRemoveBottom: PropTypes.bool,
    marginRemoveLeft: PropTypes.bool,
    marginRemoveRight: PropTypes.bool,
    marginRemoveVertical: PropTypes.bool,
    marginRemoveAdjacent: PropTypes.bool,
    marginRemoveFirstChild: PropTypes.bool,
    marginRemoveLastChild: PropTypes.bool,

    marginRemoveLeftSmall: PropTypes.bool,
    marginRemoveRightSmall: PropTypes.bool,
    marginRemoveLeftMedium: PropTypes.bool,
    marginRemoveRightMedium: PropTypes.bool,
    marginRemoveLeftLarge: PropTypes.bool,
    marginRemoveRightLarge: PropTypes.bool,
    marginRemoveLeftXLarge: PropTypes.bool,
    marginRemoveRightXLarge: PropTypes.bool,

    marginAuto: PropTypes.bool,
    marginAutoTop: PropTypes.bool,
    marginAutoBottom: PropTypes.bool,
    marginAutoLeft: PropTypes.bool,
    marginAutoRight: PropTypes.bool,
    marginAutoVertical: PropTypes.bool,

    marginAutoSmall: PropTypes.bool,
    marginAutoTopSmall: PropTypes.bool,
    marginAutoBottomSmall: PropTypes.bool,
    marginAutoLeftSmall: PropTypes.bool,
    marginAutoRightSmall: PropTypes.bool,
    marginAutoVerticalSmall: PropTypes.bool,

    marginAutoMedium: PropTypes.bool,
    marginAutoTopMedium: PropTypes.bool,
    marginAutoBottomMedium: PropTypes.bool,
    marginAutoLeftMedium: PropTypes.bool,
    marginAutoRightMedium: PropTypes.bool,
    marginAutoVerticalMedium: PropTypes.bool,

    marginAutoLarge: PropTypes.bool,
    marginAutoTopLarge: PropTypes.bool,
    marginAutoBottomLarge: PropTypes.bool,
    marginAutoLeftLarge: PropTypes.bool,
    marginAutoRightLarge: PropTypes.bool,
    marginAutoVerticalLarge: PropTypes.bool,

    marginAutoXLarge: PropTypes.bool,
    marginAutoTopXLarge: PropTypes.bool,
    marginAutoBottomXLarge: PropTypes.bool,
    marginAutoLeftXLarge: PropTypes.bool,
    marginAutoRightXLarge: PropTypes.bool,
    marginAutoVerticalXLarge: PropTypes.bool,
};

applyMargin.defaultProps = {
    margin: false,
    marginTop: false,
    marginBottom: false,
    marginLeft: false,
    marginRight: false,

    marginSmall: false,
    marginTopSmall: false,
    marginBottomSmall: false,
    marginLeftSmall: false,
    marginRightSmall: false,

    marginMedium: false,
    marginMediumTop: false,
    marginMediumBottom: false,
    marginMediumLeft: false,
    marginMediumRight: false,

    marginLarge: false,
    marginTopLarge: false,
    marginBottomLarge: false,
    marginLeftLarge: false,
    marginRightLarge: false,

    marginXLarge: false,
    marginTopXLarge: false,
    marginBottomXLarge: false,
    marginLeftXLarge: false,
    marginRightXLarge: false,

    marginRemove: false,
    marginRemoveTop: false,
    marginRemoveBottom: false,
    marginRemoveLeft: false,
    marginRemoveRight: false,
    marginRemoveVertical: false,
    marginRemoveAdjacent: false,
    marginRemoveFirstChild: false,
    marginRemoveLastChild: false,

    marginRemoveLeftSmall: false,
    marginRemoveRightSmall: false,
    marginRemoveLeftMedium: false,
    marginRemoveRightMedium: false,
    marginRemoveLeftLarge: false,
    marginRemoveRightLarge: false,
    marginRemoveLeftXLarge: false,
    marginRemoveRightXLarge: false,

    marginAuto: false,
    marginAutoTop: false,
    marginAutoBottom: false,
    marginAutoLeft: false,
    marginAutoRight: false,
    marginAutoVertical: false,

    marginAutoSmall: false,
    marginAutoTopSmall: false,
    marginAutoBottomSmall: false,
    marginAutoLeftSmall: false,
    marginAutoRightSmall: false,
    marginAutoVerticalSmall: false,

    marginAutoMedium: false,
    marginAutoTopMedium: false,
    marginAutoBottomMedium: false,
    marginAutoLeftMedium: false,
    marginAutoRightMedium: false,
    marginAutoVerticalMedium: false,

    marginAutoLarge: false,
    marginAutoTopLarge: false,
    marginAutoBottomLarge: false,
    marginAutoLeftLarge: false,
    marginAutoRightLarge: false,
    marginAutoVerticalLarge: false,

    marginAutoXLarge: false,
    marginAutoTopXLarge: false,
    marginAutoBottomXLarge: false,
    marginAutoLeftXLarge: false,
    marginAutoRightXLarge: false,
    marginAutoVerticalXLarge: false,
};

export default applyMargin;
